05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/ViewModels/Orders/CreateOrderInputModel.cs
namespace FastFood.Core.ViewModels.Orders
{
    public class CreateOrderInputModel
    {
        public string Customer { get; set; }

        public int ItemId { get; set; }

        public int EmployeeId { get; set; }

        public int Quantity { get; set; }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/ViewModels/Orders/CreateOrderViewModel.cs
namespace FastFood.Core.ViewModels.Orders
{
    using System.Collections.Generic;

    public class CreateOrderViewModel
    {
        public List<int> Items { get; set; }

        public List<int> Employees { get; set; }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/ViewModels/Orders/OrderAllViewModel.cs
namespace FastFood.Core.ViewModels.Orders
{
    public class OrderAllViewModel
    {
        public int OrderId { get; set; }

        public string Customer { get; set; }

        public string Employee { get; set; }

        public string DateTime { get; set; }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Controllers/OrdersController.cs
namespace FastFood.Core.Controllers
{
    using System;
    using System.Linq;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using Data;
    using FastFood.Models;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Orders;

    public class OrdersController : Controller
    {
        private readonly FastFoodContext context;
        private readonly IMapper mapper;

        public OrdersController(FastFoodContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Create()
        {
            var viewOrder = new CreateOrderViewModel
            {
                Items = this.context.Items.Select(x => x.Id).ToList(),
                Employees = this.context.Employees.Select(x => x.Id).ToList(),
            };

            return this.View(viewOrder);
        }

        [HttpPost]
        public IActionResult Create(CreateOrderInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            var order = this.mapper.Map<Order>(model);
            var orderItem = this.mapper.Map<OrderItem>(model);

            order.OrderItems.Add(orderItem);

            this.context.Orders.Add(order);
            
            this.context.SaveChanges();
            return this.RedirectToAction("All");
        }

        public IActionResult All()
        {
            var orders = this.context
                .Orders
                .ProjectTo<OrderAllViewModel>(this.mapper.ConfigurationProvider)
                .ToList();

            return this.View(orders);
        }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Views/Orders/All.cshtml
@model IList<FastFood.Core.ViewModels.Orders.OrderAllViewModel>

@{
    ViewData["Title"] = "All Orders";
}
<h1 class="text-center">All Orders</h1>
<hr class="hr-2" />
<table class="table mx-auto">
    <thead>
        <tr class="row">
            <th class="col-md-1">#</th>
            <th class="col-md-2">OrderId</th>
            <th class="col-md-2">Customer</th>
            <th class="col-md-2">Employee</th>
            <th class="col-md-2">DateTime</th>
        </tr>
    </thead>
    <tbody>
        @for(var i = 0; i < Model.Count(); i++)
    {
        <tr class="row">
            <th class="col-md-1">@i</th>
            <td class="col-md-2">@Model[i].OrderId</td>
            <td class="col-md-2">@Model[i].Customer</td>
            <td class="col-md-2">@Model[i].Employee</td>
            <td class="col-md-2">@Model[i].DateTime</td>
        </tr>
    }
    </tbody>
</table>

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Views/Orders/Create.cshtml
@model FastFood.Core.ViewModels.Orders.CreateOrderViewModel

@{
    ViewData["Title"] = "Create Order";
}
<h1 class="text-center">Create Order</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Orders" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Customer</label>
        <input type="text" class="form-control" id="customer" placeholder="Customer..." name="customer">
    </div>
    <div class="form-group">
        <label for="employee">Employee Id</label>
        <select id="employee" class="form-control" name="EmployeeId">
            @foreach (var employee in Model.Employees)
            {
                <option value="@employee">@employee</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="item">Item Id</label>
        <select id="item" class="form-control" name="ItemId">
            @foreach (var item in Model.Items)
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <input type="number" step="1" min="11" class="form-control" id="quantity" placeholder="Quantity..." name="quantity">
    </div>
    <hr class="bg-secondary half-width" />
    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn ">Create</button>
    </div>
</form>