05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/ViewModels/Categories/CategoryAllViewModel.cs
namespace FastFood.Core.ViewModels.Categories
{
    public class CategoryAllViewModel
    {
        public string Name { get; set; }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/ViewModels/Categories/CreateCategoryInputModel.cs
namespace FastFood.Core.ViewModels.Categories
{
    public class CreateCategoryInputModel
    {
        public string CategoryName { get; set; }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Controllers/CategoriesController.cs
namespace FastFood.Core.Controllers
{
    using System;
    using System.Linq;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using Data;
    using FastFood.Models;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Categories;

    public class CategoriesController : Controller
    {
        private readonly FastFoodContext context;
        private readonly IMapper mapper;

        public CategoriesController(FastFoodContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(CreateCategoryInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            var category = this.mapper.Map<Category>(model);
            this.context.Categories.Add(category);
            this.context.SaveChanges();
            return this.RedirectToAction("All");

        }

        public IActionResult All()
        {
            var categories = this.context.Categories
                .ProjectTo<CategoryAllViewModel>(mapper.ConfigurationProvider)
                .ToList();

            return this.View(categories);
        }
    }
}

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Views/Categories/All.cshtml
@model IList<FastFood.Core.ViewModels.Categories.CategoryAllViewModel>

@{
    ViewData["Title"] = "All Categories";
}
<h1 class="text-center">All Categories</h1>
<hr class="hr-2" />
<table class="table mx-auto">
    <thead>
        <tr class="row">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Category</th>
        </tr>
    </thead>
    <tbody>
        @for(var i = 0; i < Model.Count(); i++)
    {
        <tr class="row">
            <th class="col-md-1">@i</th>
            <td class="col-md-2">@Model[i].Name</td>
        </tr>
    }
    </tbody>
</table>

05. C# DataBase/02. Entity Framework Core/07. C# Auto Mapping Objects/Homework/FastFood.Core/Views/Categories/Create.cshtml
@{
    ViewData["Title"] = "Create Category";
}
<h1 class="text-center">Create Category</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Categories" asp-action="Create" method="post">
    <div class="form-group">
        <label for="categoryName">Category Name</label>
        <input type="text" class="form-control" id="categoryName" placeholder="Category Name..." name="categoryName">
    </div>
    <hr class="bg-secondary half-width" />
    <div class="button-holder d-flex justify-content-center">
        <button type="submit" class="btn ">Create</button>
    </div>
</form>